name: Save Spotify user tracks

on:
  push
  schedule:
    - cron: "0 0 * * *"

jobs:
  run:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Save data (run script)
      env:
        REFRESH_TOKEN : ${{ secrets.REFRESH_TOKEN }}
        CLIENT_ID : ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET : ${{ secrets.CLIENT_SECRET }}
      run: |
        python -m savetify.main
    - uses: actions/upload-artifact@v2
      with:
        name: data
        path: data.json